apiVersion: v1
kind: PersistentVolume
metadata:
      name: pv0001
      labels:
         type: local
spec:
    capacity:
          storage: 8Gi
    accessModes:
      - ReadWriteMany
    hostPath:
          path: "/data001/pv0001"
