apiVersion: v1
kind: PersistentVolume
metadata:
      name: pv0002
      labels:
         type: local
spec:
    capacity:
          storage: 5Gi
    accessModes:
      - ReadWriteMany
    hostPath:
          path: "/data001/pv0002"
